"""player_move_log added

Revision ID: 2fbb3c9ec667
Revises: 51ec240ce2fd
Create Date: 2025-10-23 12:59:51.737626

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2fbb3c9ec667"
down_revision: Union[str, Sequence[str], None] = "51ec240ce2fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playermovelog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "board_status", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("current_player_turn", sa.String(), nullable=False),
        sa.Column("game_status", sa.String(), nullable=False),
        sa.Column("related_game", sa.INTEGER(), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["related_game"], ["game.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playermovelog_created"), "playermovelog", ["created"], unique=False
    )
    op.create_index(
        op.f("ix_playermovelog_is_deleted"),
        "playermovelog",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playermovelog_modified"), "playermovelog", ["modified"], unique=False
    )
    op.create_index(
        op.f("ix_playermovelog_related_game"),
        "playermovelog",
        ["related_game"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_playermovelog_related_game"), table_name="playermovelog")
    op.drop_index(op.f("ix_playermovelog_modified"), table_name="playermovelog")
    op.drop_index(op.f("ix_playermovelog_is_deleted"), table_name="playermovelog")
    op.drop_index(op.f("ix_playermovelog_created"), table_name="playermovelog")
    op.drop_table("playermovelog")
    # ### end Alembic commands ###
