"""moves_count added to the game

Revision ID: 51ec240ce2fd
Revises: a25a3eae4f28
Create Date: 2025-10-10 01:46:51.744085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51ec240ce2fd"
down_revision: Union[str, Sequence[str], None] = "a25a3eae4f28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("moves_count", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "moves_count")
    # ### end Alembic commands ###
