"""players name added

Revision ID: 5ffdc230647d
Revises: 86acbd998028
Create Date: 2025-11-09 23:30:55.222772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ffdc230647d"
down_revision: Union[str, Sequence[str], None] = "86acbd998028"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("player_2_nick_name", sa.String(), nullable=True))
    op.add_column("game", sa.Column("player_1_nick_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "player_1_nick_name")
    op.drop_column("game", "player_2_nick_name")
    # ### end Alembic commands ###
