"""initail migration

Revision ID: 825ad2469aa8
Revises: 
Create Date: 2025-10-03 14:41:36.198452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "825ad2469aa8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("nick_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_player_created"), "player", ["created"], unique=False)
    op.create_index(
        op.f("ix_player_is_deleted"), "player", ["is_deleted"], unique=False
    )
    op.create_index(op.f("ix_player_modified"), "player", ["modified"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_modified"), table_name="player")
    op.drop_index(op.f("ix_player_is_deleted"), table_name="player")
    op.drop_index(op.f("ix_player_created"), table_name="player")
    op.drop_table("player")
    # ### end Alembic commands ###
