"""winner_name added

Revision ID: 86acbd998028
Revises: a2b8f1264d20
Create Date: 2025-11-09 23:17:58.159775

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86acbd998028"
down_revision: Union[str, Sequence[str], None] = "a2b8f1264d20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("winner_nick_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "winner_nick_name")
    # ### end Alembic commands ###
