"""created_by added

Revision ID: a2b8f1264d20
Revises: e5d3ba534bde
Create Date: 2025-11-09 20:45:27.329159

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2b8f1264d20"
down_revision: Union[str, Sequence[str], None] = "e5d3ba534bde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("created_by", sa.INTEGER(), nullable=True))
    op.create_index(op.f("ix_game_created_by"), "game", ["created_by"], unique=False)
    op.create_foreign_key(
        None, "game", "player", ["created_by"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "game", type_="foreignkey")
    op.drop_index(op.f("ix_game_created_by"), table_name="game")
    op.drop_column("game", "created_by")
    # ### end Alembic commands ###
