"""player_move_log step field added

Revision ID: e5d3ba534bde
Revises: 2fbb3c9ec667
Create Date: 2025-10-23 13:36:35.973007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5d3ba534bde"
down_revision: Union[str, Sequence[str], None] = "2fbb3c9ec667"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("playermovelog", sa.Column("step", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playermovelog", "step")
    # ### end Alembic commands ###
