"""game_sides_type added

Revision ID: ff4fb9d702aa
Revises: 5ffdc230647d
Create Date: 2025-12-05 21:35:20.601421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff4fb9d702aa"
down_revision: Union[str, Sequence[str], None] = "5ffdc230647d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("game_sides_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "game_sides_type")
    # ### end Alembic commands ###
